### ISSUE TITLE
Implement step creation wizard

### ISSUE THREAD

**Issue by danielwegener** [vbmacher/intellij-cucumber-scala#1]

**Comment by filfreire** [comment]
I'd like to help you out on this one.

**Comment by danielwegener** [comment]
@filfreire Great, good to know! As far as I remember, it would be the easiest to depend on cucumber-java and extend their step creation wizard mechanisms. I'd welcome any PR for this issue.

**Comment by wilsonr990** [comment]
Any advance on it? I could probably work on it soon.

**Comment by filfreire** [comment]
@wilsonr990 I ended up not picking this up, setting up the dev environment was confusing. 
Feel free to try to do it, if you will.

/cc @danielwegener

**Comment by suvroroy** [comment]
Folks, any word on this when this will be done?

**Comment by vbmacher** [comment]
I'm going to try to implement it now :)

**Comment by vbmacher** [comment]
Good people please try it. Step creation should work, but for now without template.

**Comment by vbmacher** [comment]
Template wizard is finished - argument names now can be changed during creation of a step in the editor.
