### ISSUE TITLE
Support cucumber-java annotations

### ISSUE THREAD

**Issue by danielwegener** [vbmacher/intellij-cucumber-scala#10]
Since the scala cucumber dsl has some restrictions and does not integrate well with cucumber-java ObjectFactories (DI-Providers), we should support scala glue code that uses java annotations (@After, @Before and so on) instead of the scala-dsl.

**Comment by bpiper** [comment]
I think this would be a very valuable enhancement, particularly for those of us who have come from a cucumber-java world where per-scenario state could be nicely managed via Guice or Spring, and are struggling to see how to do anything remotely as convenient with ScalaDSL step-defs (and therefore want to cling to the Java annotations, which seem to work just as well as in Java, IDE support notwithstanding).

Has any work been started on this already, and/or would you consider a PR? I have a rough idea of what needs to be done, but would welcome any pointers/notes.

**Comment by athieriot** [comment]
I would be quite interested by that feature as well. Happy to help also with a bit of a general direction

**Comment by danielwegener** [comment]
Hey guys. Yes - PRs on this are very welcome. I currently do not really have time to invest into this project (for me It has been some time since I have used scala together with cucumber ).

**Comment by danielwegener** [comment]
@athieriot  TBH - I don't want to call it "Lookin' for maintainer - abandoned otherwise" - but If you want to drive this project forward - I'd be happy to help out/hand over :)

**Comment by athieriot** [comment]
Fair enough !
I would say I'm interested but I'm afraid I don't have much time either to do a proper good job at it.

I'm happy to help to the extends of my abilities though.

**Comment by vbmacher** [comment]
Guys, is this feature still requested?

**Comment by vbmacher** [comment]
Closing since I think Scala DSL of cucumber has improved a lot. It seems it has all features which Java variant has (or at least I'm not familiar with any differences). Since the project is about to support cucumber-scala, in my opinion it should stick with Scala DSL.
