### ISSUE TITLE
Doesn't work with Build 212 released 27-07-2021

### ISSUE THREAD

**Issue by chrishaynes** [vbmacher/intellij-cucumber-scala#101]
**Describe the bug**
Not compatible with Build 212 of IntelliJ, released on 27th July 2021.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch IntelliJ 2021.2.
2. Show Preferences > Plugins.
3. See error: "Incompatible: requires IDE build 211.* or older".

**Expected behaviour**
Well, it should work.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7

**Comment by vbmacher** [comment]
I'm on it, hold on

**Comment by vbmacher** [comment]
DONE, try it out!
