### ISSUE TITLE
Support for IDEA 2021.3

### ISSUE THREAD

**Issue by effiban** [vbmacher/intellij-cucumber-scala#104]
Hi @vbmacher , I've just upgraded my IDEA to 2021.3 and I see that the plugin hasn't been upgraded to support it yet.
Do you have an estimate when this upgrade can be done?

Thanks

**Comment by vbmacher** [comment]
Im working on it now

**Comment by vbmacher** [comment]
Done, released

**Comment by effiban** [comment]
> Im working on it now

that's great, thanks!
