### ISSUE TITLE
IDE Internal Errors

### ISSUE THREAD

**Issue by james-work-account** [vbmacher/intellij-cucumber-scala#136]
**Describe the bug**
When using this plugin, repeatedly getting IDE Internal Error reports.

**To Reproduce**
1. Open project which uses Cucumber for Scala to link files
2. Observe IDE error

**Expected behavior**
No IDE errors

**Screenshots**
Some of the errors reported:
<img width="1595" alt="image" src="https://github.com/user-attachments/assets/eb929bb2-679a-401f-b969-8d3f54eb2a54">
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/432eb518-6881-4ada-8b59-03a37071018b">
<img width="1597" alt="image" src="https://github.com/user-attachments/assets/0f972e62-623d-4e67-adb1-29b6aaa2d7d5">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Plugin Version: 2024.2
 - IDE Version: 2024.2.0.2

**Comment by MJCallahanPage** [comment]
Same issue for me.

**Comment by ThomasGrt** [comment]
Same issue for me too

**Comment by vbmacher** [comment]
Thanks for reporting, working on it

**Comment by vbmacher** [comment]
New version of plugin (2024.2.1) was just published. Please try it!
