### ISSUE TITLE
Latest plugin 2024.2.1 does not appear in plugin list

### ISSUE THREAD

**Issue by ThomasGrt** [vbmacher/intellij-cucumber-scala#138]
**Describe the bug**
I have latest Intellij version (2024.2.1) and the update to the last cucumber-scala plugin does not appear in plugins update.
so I tried to 

- uninstall plugin to reinstall it but it doesn't appear anymore in the plugins list
- download and install it manually but it fail with following error message : 

![Screenshot_20240902_115745](https://github.com/user-attachments/assets/391b9495-a5d7-42b3-81c8-4627d45014a1)

Seems like the plugin is not targeted to latest intellij version?

By the way, thanks for the plugin!

Thomas

**Comment by richarddowsett** [comment]
![Screenshot 2024-09-02 at 12 56 43](https://github.com/user-attachments/assets/1c3b3061-1477-45bd-b5ba-9ec1398951fd)

I've found this too. The latest supported version of IntelliJ is 2024.1.6. Works like a charm in that version but it isn't supported by the latest versions of IntelliJ

**Comment by james-work-account** [comment]
I am also seeing this error - @vbmacher is this related to #136 ?

**Comment by richarddowsett** [comment]
I assume this just needs to be updated: https://github.com/vbmacher/intellij-cucumber-scala/blob/master/cucumber-scala/src/main/resources/META-INF/plugin.xml#L9

**Comment by vbmacher** [comment]
Hi guys, Im sorry I think I might have f up the compatibility range in the plugin.xml. I see in plugin marketplace the Cucumber for Scala plugin version 2024.2.1, but it seems the compatibility range is requesting old IntelliJ platform. Im going to fix it soon. Sorry, Im so busy these days and doing mistakes..

**Comment by vbmacher** [comment]
I've hopefully fixed all usability problems and published new plugin version. Please check if it works. Tests are still failing, tracked in #137

**Comment by ThomasGrt** [comment]
I've reinstalled the plugin and everything seems fine now.
Thanks! 👏🏻
