### ISSUE TITLE
Support composite string literals in step definitions

### ISSUE THREAD

**Issue by danielwegener** [vbmacher/intellij-cucumber-scala#17]
As mentioned by @sinwe in #15, it would be nice to support further literals as step definition arguments.

Examples are:

``` scala
When("concatinated "+ 
           "strings") { () => ???}
```

Problem: In the PSI model, we have an infix expression that contains string literals and the reference expression +. For this specific case, we could create a handler that detects _exactly_ this combination (multiple string literals concatinated with a `+`).

``` scala
When("""multiline
          |strings""".stripMargin) { () => ???}
```

Problem: We can get access to the whole argument as reference expressions (which we usually cannot evaluate at PSI-time) but we could match that special case where the reference expression consists of a triple-quote (potentially multiline) string followed by the expression `.stripMargin` and actually evaluate .stripMargin on it.

These are both common cases that we could handle explicitly. But they would stop working when you start mixing these concepts (multiline concatinated with a normal string literal and so on)...

**Comment by danielwegener** [comment]
My thoughts: we maybe should only support the first case, because that is essentially what you can also could do in javas annotation dsl (```@When("foo"+"bar")```). 

Java annotations only allow constants as parameters (what perfectly makes sense since they should be accessible at compile time). 
```
Error:(19, 45) annotation argument needs to be a constant; found: scala.this.Predef.augmentString("asd").stripMargin
  @JavaAnnotation(value="""asd""".stripMargin)
                                            ^
```
or 
```
Error:(19, 35) annotation argument needs to be a constant; found: scala.StringContext.apply("asd ", "").s("asd")
  @JavaAnnotation(id=s"""asd ${"asd"}""")
                                  ^
```

As already stated, the cucumber scala dsl is too powerful (in the meaning of defining step definitions - you could possibly put any computed value into a call to `When` and friends ) to create a proper pre-runtime tooling support.

**Comment by avokin** [comment]
To calculate string concatenation it's possible to use `PsiConstantEvaluationHelper`:

```
            PsiConstantEvaluationHelper evaluationHelper = JavaPsiFacade.getInstance(project).getConstantEvaluationHelper();
            Object constantValue = evaluationHelper.computeConstantExpression(expression, false);
```

**Comment by danielwegener** [comment]
Hi @avokin! Thanks for your suggestion. Is there something equivalent for the `PsiConstantEvaluationHelper ` provided by the `JavaPsiFacade` also support scala literals? Or is there any equivalent for the scala psi model?

**Comment by avokin** [comment]
Sorry for late reply, I missed notification. I've found `org.jetbrains.plugins.scala.lang.psi.util.ScalaConstantExpressionEvaluator` in Scala Plugin for IDEA.

**Comment by vbmacher** [comment]
Thanks for the tip, I tried it, and it seems it works.

**Comment by vbmacher** [comment]
What should work now:

```scala
  When("I sub (\\d+)" + " and " + "(\\d+)") {
    (arg1: Double, arg2: Double) =>
      calc push arg1
      calc push arg2
      calc push "-"
  }

  When("I div " + (5 + 5) + " by " + (10 - 8)) {
    calc push 10.0
    calc push 2.0
    calc push "/"
  }
```

In feature file: 

```
  Scenario: Subtracting
    When I sub 4 and 5
    Then the result is -1

  Scenario: Dividing
    When I div 10 by 2
    Then the result is 5
```

**Comment by vbmacher** [comment]
But calling a function inside definition (even if it's a `val`) does not work.

**Comment by danielwegener** [comment]
Yeah I think we can not get any better :) nice

**Comment by vbmacher** [comment]
Released in https://github.com/vbmacher/intellij-cucumber-scala/releases/tag/2020.1
