### ISSUE TITLE
Scenario Outline broken?

### ISSUE THREAD

**Issue by Hallborg** [vbmacher/intellij-cucumber-scala#32]
I got some highlighting issues for Scenario outlines in the latest version of the plugin. (for intellij 2017.3)

1. Some text get the wrong colors in the feature files.
![highlight_issue_1](https://user-images.githubusercontent.com/7092252/33992425-cecd9b8a-e0d2-11e7-920d-72de38190178.png)

2.  refactoring placement values will report as missing step definition (will be fixed on restart of intellij)

This is before the refactoring
![highlight_issue_2](https://user-images.githubusercontent.com/7092252/33992565-6ef77716-e0d3-11e7-8a8b-a47da56ae970.png)
and this is after
![highlight_issue_3](https://user-images.githubusercontent.com/7092252/33992624-a870c9b6-e0d3-11e7-94e4-662a8f376fa6.png)

Any idea on what is causing this?

**Comment by danielwegener** [comment]
intellij-cucumber-scala is only responsible for the linking between feature file lines and glue-code using the cucumber-scala api from the `cucumber.api.scala` package. I am not sure if the "plain" cucumber-plugin for intellij has changed the highlighting in 2017.3. Can you reproduce the same behavior using the java-dsl (`@Given/@When/@Then` annotations)?

**Comment by vbmacher** [comment]
I have tested it with current version of plugin and it works. Attaching screen-shot.
![Screenshot from 2020-04-12 20-58-02](https://user-images.githubusercontent.com/344077/79077280-c06c0c80-7d00-11ea-850b-6a1136d649d5.png)

**Comment by vbmacher** [comment]
Also, after refactoring the `v` to `value` still works. The step is defined as:

```gherkin
  Then("is a <(.*)>") {
    exp: String =>
      println(exp)
  }
```

**Comment by vbmacher** [comment]
I'm going to close this.
