### ISSUE TITLE
Glue code no longer recognized in traits since latest update

### ISSUE THREAD

**Issue by zsolt-donca** [vbmacher/intellij-cucumber-scala#54]
Glue code defined in traits no longer appears to be recognized by the plugin since the IntelliJ 2020.1 update; it worked fine on IntelliJ 2019.3.

In our codebase, we like to organize our glue code into separate traits, which we all mix together into a single class. So we have something like this:

```
trait BaseGlue extends ScalaDsl with EN {
  When("doing something special") {

  }
}

class MyGlue extends BaseGlue
```

The step `When doing something special` is not recognized in the .feature file (it is highlighted yellow), and thus highlighting its parameters or navigating to the step definition do not work.

As a workaround, we could refactor so that all our glue code is defined in classes.

I am at IDEA version:
```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
```

My "Cucumber for Scala" plugin is at version `2020.1`.

**Comment by vbmacher** [comment]
Yes, I confirm that. Thank you for reporting

**Comment by vbmacher** [comment]
You can test it against the `development` branch. It should work now.

**Comment by zsolt-donca** [comment]
Thank you, I can confirm that the latest build from `development` works!

**Comment by vbmacher** [comment]
You're welcome :)
