### ISSUE TITLE
Prepare for upgrade of cucumber-scala to 5.x

### ISSUE THREAD

**Issue by vbmacher** [vbmacher/intellij-cucumber-scala#62]
There are lot of changes in cucumber-scala project happening now, bringing more Java-like compatibility. See https://github.com/cucumber/cucumber-jvm-scala/blob/master/docs/upgrade_v5.md

**Comment by gaeljw** [comment]
I was just about to open the issue as I noticed that navigation in feature files doesn't work anymore while I'm working on the 5.x branch...

If I can help, please tell me :)

**Comment by vbmacher** [comment]
Hi Gael, I kind of expected that. I didn't study the cucumber-scala changes yet, but I had the feeling like the changes are breaking so I preventively opened the issue :) 

Regarding your offer - would you like to implement it? I would be happy if you do. For now, I didn't know if the cucumber-scala code is finished (I think it's not released yet) so therefore the name "prepare" in the title.

**Comment by gaeljw** [comment]
Indeed, nothing released yet. I'd like to include some other stuff before releasing, I guess we can expect a release by the end of this week or the next one.

I don't know the plugin code but I guess the only breaking change with impact is the package renaming.

I can sure have a look and open a PR ;)

**Comment by vbmacher** [comment]
If the package name change is the only thing (haven't tried it yet), it should be enough to change constants in `ScCucumberUtil`:

```
  private final val CUCUMBER_SCALA_STEP_DEF_TRAIT = "cucumber.api.scala.ScalaDsl"
  private final val CUCUMBER_SCALA_PACKAGE = "cucumber.api.scala"
```

**Comment by gaeljw** [comment]
Do you think it's possible to be backwards compatible?
It will take some time for people to use the new Cucumber Scala 5.x and it would be great if the plugin could navigate from feature to step, no matter if Cucumber Scala 4.x or 5.x is used in the project.

The template definition will probably be for 5.x with a comment saying how to make it 4.x compatible.

**Comment by gaeljw** [comment]
I've open a draft PR to which we can have a look when Cucumber Scala 5.x is released.

I don't know how to test it though. Building locally and installing the plugin locally on my IntelliJ instance maybe?

**Comment by vbmacher** [comment]
I was thinking exactly the same - if we can make the changes bw compatible. I think we can, because plugin real dependencies do not include cucumber-jvm-scala, fortunately - it operates just on the syntax level.

**Comment by vbmacher** [comment]
And thanks for PR btw, it looks OK to me. Regarding testing, this project unfortunately does not have unit tests yet. So for now, there are two options:

- compile and install plugin locally
- run `runIde` gradle task which runs dev version of IntelliJ installed with just needed plugins - ie. gherkin, java, cucumber-java, scala, and intellij-cucumber-scala.

I use the second option, and when it is loaded I just open the same project.. It's good to copy it first to some other place, because we would have opened the same project twice in Idea and I observed this setup causes some issues.

**Comment by gaeljw** [comment]
I just made the PR "ready for review" @vbmacher ;)

**Comment by vbmacher** [comment]
I have merged the code, thanks for your work :) I think we can now close this issue.

**Comment by gaeljw** [comment]
Sorry but I think you closed the MR without merging because I've got this message: _This pull request is closed, but the gaeljw:ready-for-v5 branch has unmerged commits_ and merging should have closed the issue automatically :thinking:

**Comment by vbmacher** [comment]
Oops, I thought it's been merged, sorry. I've reopened the PR, and merged it now. Thanks for pointing out..
