### ISSUE TITLE
The step definitions do not autocomplete in Idea 2020.1

### ISSUE THREAD

**Issue by dinchand** [vbmacher/intellij-cucumber-scala#73]
**Describe the bug**
Scala step definitions do not autocomplete but the tests succeed. And  tried to add a step with java @When which seems to work fine.

**To Reproduce**
[examples.zip](https://github.com/vbmacher/intellij-cucumber-scala/files/4875756/examples.zip)

**Expected behavior**
Autocomplete should work

**Screenshots**
![image](https://user-images.githubusercontent.com/10563045/86543105-d104db00-bf1b-11ea-9afd-ab2ba0eef6af.png)
![image](https://user-images.githubusercontent.com/10563045/86543127-16290d00-bf1c-11ea-8876-1da234a2f30a.png)

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
Could you may be point out possible issues ? Just tried to add a step with java @When which seems to work fine

**Comment by vbmacher** [comment]
Hi! Have you tried it within Idea 2020.2 EAP? For 2020.2 there is new version of the plugin which fixes many things.

Version of Idea 2020.2 should be released this summer (https://confluence.jetbrains.com/display/IDEADEV/IDEA+2020.2+latest+builds) so it does not make sense for me to fix the plugin for earlier versions.

**Comment by dinchand** [comment]
Tried now with 2020.2 EAP. Somehow the plugin installation says not compatible

**Comment by dinchand** [comment]
Unable to add attachments but plugin version 202.5958.24-EAP-SNAPSHOT
Intellij EAP version 2020.2 EAP build 202.6109.22

**Comment by vbmacher** [comment]
Oh that's why. Since 2020.2 is still not released, Jetbrains still changes API (with new builds) effectively making this plugin incompatible. For testing you need specific version - 202.5958.24. 

I am gradually updating EAPs to new builds as they come and re-releasing the plugin, but it take some time.

**Comment by vbmacher** [comment]
Ok, so you might try using new release of the plugin: https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala/update/91071 . It's ready for Idea 202.6109.22

**Comment by dinchand** [comment]
@vbmacher Thanks a lot. Works perfectly now ! Also saw the other ticket about auto-complete of Step definitions from libraries. This plugin version is definitely a great improvement. Kudos !!!!

**Comment by vbmacher** [comment]
Glad to hear! And thank you for feedback :) I'm closing the issue now.
