### ISSUE TITLE
Intellij 2020.2 update

### ISSUE THREAD

**Issue by vbmacher** [vbmacher/intellij-cucumber-scala#75]

**Comment by james-work-account** [comment]
I'm unable to navigate through Feature files in IntelliJ 2020.2 - am I missing something? I have the following installed:

- IntelliJ Ultimate version: 2020.2
- Plugins:
  - Scala 2020.2.23
  - Cucumber for Scala 2020.2
  - Gherkin 202.6397.21

**Comment by vbmacher** [comment]
@james-work-account Please create new ticket and describe your problem in more detail, possibly include screenshots. Quick tip: has indexing finished when you tried to do the navigation?
