### ISSUE TITLE
Upgrade to Scala 2.13.3

### ISSUE THREAD

**Issue by netherial** [vbmacher/intellij-cucumber-scala#80]
If possible with Cucumber 6.8.* - but mainly the Scala version is important in this feature request.

**Comment by vbmacher** [comment]
Thanks for the request, @netherial .

I must do some analysis first. This plugin is traversing Scala AST and Scala Psi model when looking for step definitions. I don't know what is different in Scala 2.13. I hope it will be compatible / no-change.. If not, I don't know if it is a good idea to have 2 plugin versions for various Scala.

**Comment by netherial** [comment]
Thank you @vbmacher for analyzing this. I hope it will be a quick win.
I am looking forward to the outcome of your investigation.

**Comment by vbmacher** [comment]
So, I did some analysis on this. Actually I didn't realize that doesn't matter on Scala version at all. Because Scala plugin in IntelliJ is able to handle any Scala version and it parses it into unified Psi structure. So this requirement doesn't need any changes - it should work out of the box. I tried it, and it works. Did you actually try it?

**Comment by netherial** [comment]
Hmm, that's surprising. I've tried it already with multiple IJ versions (2019.1.1, 2020.2.3) but it does not work for me.
How could I debug / figure out what is the problem then in the background?

I am wondering if there is any special requirement for the plugin regarding the project structure.
Currently my project where the plugin is tested and not working:
- runs with Gradle 6, Java11 and Scala2.13. 
- has multiple Gradle sub-modules in the project and I use Cucumber-Scala in one of them
- runtime the cucumber feature files are matched with scala step definitions

**Comment by vbmacher** [comment]
I'm sorry I didn't have much time on weekend to look at it. However what I did was I upgraded example from this project to Scala 2.13 (just example, not complete project) and used standard plugin installed from Plugin portal. It had matched step definitions and feature files as expected. 

But I believe you there might be some cases in which it doesn't work. It would be very helpful if you could provide a minimal example which doesn't work so I can start from there. Thank you!

**Comment by netherial** [comment]
Is that possible that the cause is the Cucumber version? I use Cucumber 6.8.1.
I am going to try it with a lower version as well to compare the results.

When I done with this without luck I will prepare a small sample project to demonstrate the issue.

**Comment by vbmacher** [comment]
It is possible. I will update the plugin now for IntelliJ 2020.2.3 and Cucumber 6.8.2

**Comment by vbmacher** [comment]
Please update your plugin and let me know if it works or not, thanks!

**Comment by netherial** [comment]
I've verified it and works properly. Thank you for the update Peter! 🥇
