### ISSUE TITLE
Not working on 2020.3

### ISSUE THREAD

**Issue by aartigao** [vbmacher/intellij-cucumber-scala#83]
Hey! Just updated the plugin along with latest 2020.3 IntelliJ and:

```
Plugin 'Cucumber for Scala' (version '2020.2.3') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IC-203.5981.155
```
I guess something needs to be changed in order to work with current build. I can't help much more, because never seeing the internals of an IJ plugin but hope the message is meaningful to you 😄

**Comment by vbmacher** [comment]
Hey @aartigao , the plugin needs to be updated with newest version of IntelliJ SDK. It's a manual process, because it might involve code changes (solving incompatible API or fixes). Let me look at this one, thanks!

**Comment by vbmacher** [comment]
Plugin has been updated, fixed and released. Enjoy :)
