### ISSUE TITLE
Enable matching custom parameter types

### ISSUE THREAD

**Issue by vbmacher** [vbmacher/intellij-cucumber-scala#88]
The request initiated in https://github.com/vbmacher/intellij-cucumber-scala/pull/85 . This PR introduces just matching any text between `{}` as `.*` regex enabling to match custom types.

It will be nice if it translated into custom-type regex as defined in the code. I'm not sure if that's even possible since the code would need to be interpreted - custom types are recognized at runtime. Well, I'd like to try at least.

More info on the topic:
- https://cucumber.io/docs/cucumber/cucumber-expressions/#custom-parameter-types

**Comment by vbmacher** [comment]
Possible algorithm:
- Find valid `ParameterType` definitions (make sure they're from ScalaDSL) which are in scope
- If a parameter type is involved, try to find regex there and use that as replacement in `ScStepDefinition.replaceParametersWithRegex`

**Comment by vbmacher** [comment]
ParameterTypes can be defined:
- by calling `def ParameterType(name, regex)` method
- or by creating `new ParameterTypeBody(name, regex)`

**Comment by vbmacher** [comment]
It seems that algorithm outlined in https://github.com/vbmacher/intellij-cucumber-scala/issues/88#issuecomment-747317234 works. Currently, it recognizes `ParameterType` definitions in scope of any step definition. What won't work is registration of `ParameterType` in `before` or `beforeAll`. I don't know if this is actually valid from cucumber-scala point of view.

**Comment by gaeljw** [comment]
> What won't work is registration of `ParameterType` in `before` or `beforeAll`. I don't know if this is actually valid from cucumber-scala point of view.

I'm late to the party but this is not something we encourage or document either. Actually, I think it wouldn't event work.

By the way great work on the latest release 👍

**Comment by vbmacher** [comment]
Thank you @gaeljw, I should have asked you earlier. I also thought using ParameterType in `before` is weird, but I wasn't quite sure about `beforeAll`. Anyway, the plugin doesn't support any of those.

And also thanks for nice words! The work I do here is only possible because of improvements of cucumber-jvm-scala ;)
