### ISSUE TITLE
Unable to type some characters in DocStrings

### ISSUE THREAD

**Issue by gaeljw** [vbmacher/intellij-cucumber-scala#89]
**Describe the bug**

When writing a scenario in a `.feature` file, inside a DocString block (`"""..."""`), some characters like the comma (`,`) are automatically removed by IntelliJ.

**To Reproduce**

1 - Create a feature file like this:

```gherkin
Scenario: Do something
  When I send this bunch of JSON
    """
    {
      "key1": "val1",
      "key2: 10
    }
    """
```

2 - Try to add `, "key3": "val3"` at the end of the "key2" line by typing it (not copy-paste)

3 - The comma disappear by itself!

4 - If you remove the `"""`, typing work as expected.

**Expected behavior**
The comma should not disappear.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora
 - IntelliJ 2020.2.3 (I've had the issue for several releases)

**Additional context**
Maybe this has nothing to do with the Cucumber Scala plugin but I don't have much other plugins installed. I find this very weird.

**Comment by vbmacher** [comment]
Hi @gaeljw , this is odd! I didn't find time to check this in my Idea, but on the first sight it looks like issue of Scala plugin. Scala plugin parses `.scala` files and provides features like code highlighting, intentions, etc. 

Cucumber IDEA plugin on the other hand uses AST or Psi tree from Scala plugin and it does not change it. It actually changes it only when a step definition is to be generated via template, but this is not the case.

I can try to find the cause, but maybe sometimes next week

**Comment by gaeljw** [comment]
Indeed, I just spent few minutes to disable plugins one by one and the curlprit is Scala plugin, not related to Cucumber plugin.

Thanks for taking time to read :)
