### ISSUE TITLE
Support for IntelliJ 2021.1

### ISSUE THREAD

**Issue by cameron-russell** [vbmacher/intellij-cucumber-scala#98]
The step definitions in .feature files can no longer be found in IntelliJ 2021.1.

JetBrains Scala plugin version: 2021.1.16
JetBrains Cucumber for Java plugin version: 211.6693.111

**Comment by vbmacher** [comment]
Thanks for reporting!

**Comment by vbmacher** [comment]
Support for IntelliJ 2021.1 is now released. Enjoy!
